### ISSUE TITLE
Create a prototype motions corpus

### ISSUE THREAD

**Issue by ninpnin** [swerik-project/riksdagen-motions#2]
We need 
- [x] A schema
- [x] Draw a sample and format it acc. to the schema
- [x] Create the v0.1.0 motions corpus

(Continuation of https://github.com/welfare-state-analytics/riksdagen-corpus/issues/400)

**Comment by BobBorges** [comment]
https://github.com/swerik-project/riksdagen-motions/releases/tag/v0.1.0
https://swerik-project.github.io/riksdagen-motions/
