### ISSUE TITLE
multi-motion pages -- split or no?

### ISSUE THREAD

**Issue by BobBorges** [swerik-project/riksdagen-motions#7]
Some motions are so short that there are several on a page. I've found instances where there are three consecutively numbered files with the exact same content, e.g.:

![image](https://github.com/user-attachments/assets/801c846c-c2ac-4178-8549-fa94aab337fc)

I think leaving it like this will cause all kind of estimate inaccuracies and unnecessary challenges for users of the corpus. 

Two options: 
- leave the multi-motion pages, but merge the three files -- one file `mot-1970--fk--88-90.xml`
- remove text from files that it doesn't belong in -- i.e. remove the text from motion 89 and 90 from `mot-1970--fk--88.xml`. Leave the page breaks and running heads (`<fw></fw>`).

I think the second option is cleaner and would opt for that approach, esp. since each file should a metadata block for a single document. Any thoughts from the rest of you? @MansMeg @fredrik1984 @ninpnin

**Comment by fredrik1984** [comment]
Thanks for this Bob! This will most likely be more (only) common during bicameral riksdag. Between 1867–1970, all (?) submitted motions 1867–1970 had to have a doublicate/reference motion in the other chamber. The doublicate motions were only shorter summaries of motion id, title, and signing MPs. We can discuss this with Lotta on Thursday.

I would say that option 2 is the best one here. It will be messy to connect MPs to the right motion otherwise.

**Comment by ninpnin** [comment]
I agree with the second option. However, removing text is potentially dangerous, so we gotta be careful. Is the content exactly the same on all of these? Then we could write a unit test to check that the combined content matches the source file.

**Comment by fredrik1984** [comment]
Good point. But do we need to remove text? Is it not better to "ignore" these motions that are not tied to the relevant motion? Or does removing and ignoring mean the same thing in your world?

**Comment by BobBorges** [comment]
It's not really deleting anything, since the text is the same in all three files, we remove _some_ text from _some_ files, but not all the text from any of them, and not any particular piece of text from everywhere.

Our motion 88.xml will only contain text of motion 88. 89.xml, only text related to motion 89, etc.

@ninpnin: agreed. I will test the content is the same on such cases before taking any further action.

**Comment by BobBorges** [comment]
right now there are some issues with the OCR that was done months ago and I'm working faster than the OCR can keep up --- as soon as there's text from the whole period, I will make a release. 

For  motions coming from alto, for those I do have already that is, this is the next step -- It has to be done in order to ID the titles/signature blocks and fill in the metadata.

**Comment by BobBorges** [comment]
in the 1920s, the förteckning is mixed in... this needs to get separated out too.
